name: LavaLocationManager
version: '${project.version}'
main: club.lavaer.lavalocationmanager.LavaLocationManager
author: Lava_er

depend: [PlaceholderAPI]

commands:
  LocationManager:
    usage: "/<>"
    description: "LocationManager"
    aliases: ["lm", "llm", "vlm"]